### ISSUE TITLE
Configuring the UI

### ISSUE THREAD

**Issue by jopopcorn** [euphony-io/soundless-check-in#1]
### Configuring the UI
* UI sketch
* UI mark up

**Comment by sujin9** [comment]
Here's simple UI sketch !
![sample_eng](https://user-images.githubusercontent.com/8490058/129478927-d92ac982-9ce6-492f-b283-c73a6a66a5c7.png)
Please let me know if you have any questions or feedback ! :)

**Comment by jopopcorn** [comment]
Nice sketch! I think would be good to do it like this.
But I'd like to make two corrections in Android widget.

1. Set inputType phone number in EditText attribute
It would be convenient to print user information on the MainActivity if you specify the input type.

2. Use Spinner to get residence information
If you input all the regions of Korea, users will be able to respond easily.

I'll design it briefly based on the sketch and upload it tomorrow.

**Comment by jopopcorn** [comment]
I designed it simply based on the sketch. 😊
Please give me your opinion if there's anything to fix!

<img width="1116" alt="img_design" src="https://user-images.githubusercontent.com/35393459/129588244-a0612b7c-1db9-45f3-bab2-59e378721597.png">

**Comment by sujin9** [comment]
It;s cool ! Thanks for the design :)
But I'm wonder, if we use spinner to get city information, do we need to use more than 2 spinners?
Because there're so many cities in Korea !
Or How about using EditText for user to entering their region directly?

**Comment by aiclaudev** [comment]
It's so nice and simple design! The simpler the design, the more convenient it will be.

But, I wonder why the texts is English. 
How about set the texts to Korean? It is more easier for elderly to use this application.

And there is a EditText to set visitor's information, but there is no EditText to set store's information.
is there any way to set store's information?

Thank you for your hard work, it is greatly appreciated :)

**Comment by JuSeongPil** [comment]
@aiclaudev 

> And there is a EditText to set visitor's information, but there is no EditText to set store's information.
> is there any way to set store's information?

Hi dohyeon.
The stores have there own number.
They have "Bussiness number" that can detected there store location by customer.
How about using this information on EditText?
Thank u :)

**Comment by aiclaudev** [comment]
> @aiclaudev
> 
> > And there is a EditText to set visitor's information, but there is no EditText to set store's information.
> > is there any way to set store's information?
> 
> Hi dohyeon.
> The stores have there own number.
> They have "Bussiness number" that can detected there store location by customer.
> How about using this information on EditText?
> Thank u :)

Putting  the "Business number" instead of "customer's number" is so nice idea.
Really appreciate for your feedback!
