### ISSUE TITLE
Configuring PR Template

### ISSUE THREAD

**Issue by jopopcorn** [euphony-io/soundless-check-in#21]
* Create a PR template so that we can create PR based on the form.

**Comment by sujin9** [comment]
Yeah it's good! Thanks!
And I have one opinion here, 
> ## What does this PR do? Please write it down in detail.
How about say this more in detail? - What's the problem, how you solve this ...

**Comment by aiclaudev** [comment]
> Yeah it's good! Thanks!
> And I have one opinion here,
> 
> > ## What does this PR do? Please write it down in detail.
> 
> How about say this more in detail? - What's the problem, how you solve this ...

It's so nice idea Thanks for your opinion. :)
