### ISSUE TITLE
Set gitignore

### ISSUE THREAD

**Issue by sujin9** [euphony-io/soundless-check-in#3]
- To ensure that specified files not tracked by git.
- Choose which files to add to gitignore

**Comment by sujin9** [comment]
Just added a commit with this issue!
Please check the file and let me know how it is ! :)

Referred to [Euphony/.gitignore](https://github.com/euphony-io/euphony/blob/master/.gitignore)

**Comment by jopopcorn** [comment]
The .idea directory typically contains different paths or settings for each user.
Therefore, I would recommend adding `.idea/*` to .gitignore!
